#!/usr/bin/with-contenv bash
MIRROR=${MIRROR:-http://dl-cdn.alpinelinux.org/alpine}
PUID=${PUID:-911}
PGID=${PGID:-1001}

cat << "EOF"
-------------------------------------
             _           _                
     /\     | |         (_)               
    /  \    | |  _ __    _   _ __     ___ 
   / /\ \   | | | '_ \  | | | '_ \   / _ \
  / ____ \  | | | |_) | | | | | | | |  __/
 /_/    \_\ |_| | .__/  |_| |_| |_|  \___|
                | |                       
                |_|                       

-------------------------------------
EOF

if [ $PUID -ne 911 ] || [ $PGID -ne 1001 ]; then
    groupmod -o -g "$PGID" alpine
    usermod -o -u "$PUID" alpine
fi

echo "
GID/UID
-------------------------------------
User uid:    $(id -u alpine)
User gid:    $(id -g alpine)
-------------------------------------"

sed -i "s#http://dl-cdn.alpinelinux.org/alpine#$MIRROR#g" /etc/apk/repositories
